////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
This screen includes details that need to create sprint.

== Fields Description
. "Sprint Name" field should contain the name of sprint.
. "Description" field should contain the description of sprint.
. "Start Date" field should contain the starting date of the sprint.
. "End Date" field should contain the ending date of the sprint.
. "How many Sprint Backlog(s)?" field should contain how many Sprint Backlog do you want from the top of Product Backlog.

== How to create the sprint
. Fill all of fields.
. Click at the submit button.

= Update Sprint.
This part use to update Sprint backlog such as planned hours, ....

. Product Name
. Sprint Name
. Sprint Goal
. Status
. Start Date
. End date
. Planned Hours  (Integer or floating point).
. Sprint Length Weeks
. Click the update button to update the Sprint Backlog.
