////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Scrum Members
Any activity in any of the Scrum actions need people who are members of the project.

So create the people which will be involved in the "Members Tab".
You need to enter an existing person and company (partyGroup). +
Persons and companies (PartyGroup) need to be added in the party component first before they can be used in the Scrum component.

== Add members into scrum component
The purpose of this is to add member into the scrum component.
There are 3 screenlets to perform on the screen include with:

. Find Scrum Member
. Add Scrum Member
. Scrum Members List


== Find Scrum Member
To find member who is in the Scrum Component.There 5 criterias to identify - Company,Last Name,First Name,Middle Name and Group Id.

Then, click the button "Find" the solution will display on the Scrum Members List screenlet.

== Add Scrum Member
To add the member the Scrum Component by selecting at Company and Person and Group Id.
Then, click the button "Add" the solution will display on the Scrum Members List screenlet.

== Scrum Members List

This screenlet will show all of member who are in the Scrum Component by default.
There is the remove button for each list to remove member out form the Scrum Component.