////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Default Tasks
This screen use for setting the task that will be generated automatically when the backlog is create.
The screen consists of :

. Create A Default Task button
. Default Task List


== Create A Default Task button
To create a new default task.
When click on the button the screen appears  Edit Default Task instates the Default Tasks List.

== Default Tasks List
To show Default Tasks List,when click it's name the screen appears  Edit Default Task.

== Edit Default Task
The screen appears the criteria that can be updated.