////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Categories
== List of ProductBacklog Categories
This screen use for classification of the ProductBacklog.
The screen consists of :

. New Category button
. Product Backlog Categories

== New Categories button
To create a new categories.
When click on the button the screen appears  Edit Product Backlog Category instates the Product Backlog Categories List.

== Product Backlog Categories
To show Product Backlog Categories List,when click it's number the screen appears  Edit Product Backlog Category.

== Edit Product Backlog Category
The screen appears the criteria named "Category" to create a new category.