////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
== Project/Sprint
Now that we have a project backlog it is time to hold a project meeting.
In this project meeting discuss the goals of the project, the organization and the product backlog items and
the estimated hours to complete each item.

Now create the project in the system and assign the members to the project with their roles.
Attach the minutes of the meeting to the project.

=== Sprint list (and project)
The Sprint List list all the projects and for each the list of its Sprint.

* It's possible to click on Project Name to open Project overview
* It's possible to click on Sprint Name to open Sprint overview

=== Project
==== Create New Scrum Project
This screen includes details of Scrum project information fields that user have to be filled and then press
create button for creating new one.

1. User can add Project Name, Description, Status, and Estimate Start Date
2. Click 'Create' button when adding finish.
3. There is project list to display relate with your project and user can update project than user created.

==== Project Overview
This screen displays Informations of the project.
There are sprint, member and other.

==== Project Contents
This screen use for uploading any contents that concern to the project.
The screen consists of :

. Project Content List
  * show the list of contents by Content Type Id and Content Name. +
    There are 2 buttons in each content:
    .. Delete : To delete the uploaded content
    .. Download : To download the uploaded content
. Add Project Content
  * To upload the content. +
    The content can be classified by choosing the Content Type Id and Mime Type Id.


=== Sprint

==== Sprint overview, Burndown Chart
Keep an eye on the burndown chart if you are still on track.
If not discuss with the product owner if backlog items have to be added or removed.

A burn down chart is a graphical representation of work left to do versus time. +
The outstanding work (or backlog) is often on the vertical axis, with time along the horizontal.

That is, it is a run chart of outstanding work. +
It is useful for predicting when all of the work will be completed.

The hour burndown chart provides you with the following information:

. Actual Hours -- The number of hours remaining until the version release date.
. Planned Hours -- The minus of the previous planned hours and the current actual hours.
. Ideal Hours -- The ideal burndown. This is computed with the remaining estimates,
                not the original estimates of the hours remaining at the version's start date.
. Daily Completed -- The total time worked by the team (the current actual hours).

==== Create the first sprint
Now that there is a project we can look at creating the (first) sprint.
Have a Sprint meeting, define what should be implemented in the (first) sprint and how it should be implemented

Create now the (first) sprint in the system and enter also the number of backlog items which will be included in this sprint.
Attach the minutes of the meeting to the project.

. "Add Sprint" button, press it if you want to create the sprint (Only Scrum Master can see this button).
. "List of Sprint" form, contained and display the all of sprint in the system.

include::scrum-add-sprint.adoc[leveloffset=+3]

==== Member
This screen includes

* Add Sprint Backlog
  . Select the Project Members Drop down list, then Role Type Id will auto appear.
  . Set From date to member attack to the sprint and set Thru date to get the member out of the sprint
* print member list.
  . Show the print member list.There is a Remove button for set member out of the Sprint.

==== Add Sprint Backlog
This screen use to add product backlog item(s) that need in this sprint.

. Enter number of product backlog item(s) that need in this sprint.
. Click submit button when insert above field.
. *product backlog item(s) that are stored in this sprint come from top of product backlog.

==== Create tasks on the sprint backlog items
In order to be able to enter actual hours it is required to create at least a single task on every sprint backlog item.

==== Update daily the actual and planned hours
Before going to the daily sprint meeting make sure the planned (backlog item) and actuals (tasks) are updated.

==== Daily sprint meeting
Have a daily sprint meeting where the three famous questions are answered and enter the answers in the system related to
this sprint.

Daily Scrum, brief, daily meetings (about 15 min) between the Scrum Master and the Scrum Team. +
The purpose is to keep work flowing smoothly and eliminate any impediments.

There are 3 perspectives to talk in meetings :

. What have you accomplish since the last meeting?
. What are you going to do before the next meeting?
. What problem are you having with to task?

=== Content data
There is 3 level for uploading content.

. Project Content
. Product Content
. Product Backlog Content
