////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Birt Apache OFBiz® plugin
The Apache OFBiz Project
Release 17.12
:imagesdir: ./images
ifdef::backend-pdf[]
:title-logo-image: image::OFBiz-Logo.svg[Apache OFBiz Logo, pdfwidth=4.25in, align=center]
:source-highlighter: rouge
endif::[]

The birt plugin is one of the OFBiz plugins.

== OFBiz Flexible Reports
One of the functionalities of the birt plugin are the "OFBiz Flexible Reports"

NOTE: This feature will begin to be officially available with the R17.12 branch first release

There is an anounce with some history in the OFBiz blog:  
https://blogs.apache.org/ofbiz/entry/the-birt-flexible-reports-a[Reporting in Apache OFBiz® and the OFBiz Flexible Reports]     

=== Technical Documentation
include::_include/bt-creating reports.adoc[leveloffset=+1]
include::_include/bt-using the birt report designer.adoc[leveloffset=+1]
include::_include/bt-report master creation.adoc[leveloffset=+1]
=== User documentation
include::_include/bt-how to use flexible reports.adoc[leveloffset=+1]

