////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= My portal Plugin

Within the 'my portal' application it is possible to create a collection of screens for a specific type of user of the system.

Examples are a general employee, an account manager, a customer, a supplier etc...

The system makes use of special portlets which can be arranged and selected/hidden by the logged on user.

The MyPortal application is an example of what it's possible to do with OFBiz Portal technics
(integrated in ofbiz framework)

== Some Portlet in other components

include::_include/portlet-system-info-notes.adoc[leveloffset=+2]

include::_include/portlet-calendar.adoc[leveloffset=+2]
