////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= SPA / FrontJs with Vue.Js

SinglePageApplication or GUI done with a front done with a Javascript framework

done with *Vue.Js framework*, and *Vuetify Material-Design library*

vuejs component included a *FrontJs-Renderer* (similar as Macro-Renderer) usable to handle user interface with modern javascript
framework (Vue.Js, React, Angular, ect...) to be able to build a Single Page Application for one or more OFBiz component.

It use the standard OFBiz Widget System defined by XML and a vuejs application.

This component is currently at Work In Progress state,  it aims to concretely build  applications/components in order
to discuss the development process and the use of the application. +
It is produced in an "Agility" spirit which mean that it focus to result in despite of some technical debt.
Currently there are still some TODO in the code and choice has been made to implement only xml tags and attributes which are used,
at least, in one application/component.

XML tag or attribute not yet implemented generate warning or error.

This documentation aim to,

* Explain the current state of the component, how it work and which points had been choose or took away.
* Document how to use it to develop OFBiz application by explaining each specific item by example.

The two main goal of using a javascript framework for user interface is

1. to have a "modern" look and feel
  * using recent GUI library
  * usable in multiple context (PC, tablet, smartphone)
1. to increase interactive elements in screen, even if theses screens are based on standard modules :
  * update some part of the screen by action or by data update;
  * modify forms field as function of other field values;
  * simpler screen configuration without having to worry about screenlet interaction.

include::_include/vuejs-renderer.adoc[leveloffset=+1]

== modular and generic UI
Aiming to have an open and modular ERP, it's important that the user interface configuration allow to manage multiple screens
from a set of screen "module" for manage *same business object* type in *different business context*.

Next chapters describe a user interface management system's POC aiming to respond to theses modularity needs.

include::Ui-POC.adoc[leveloffset=+2]


== Screenlet autonomous
in a modular approach, screenlet is an autonomous part of the screen, which mean that there can be action that only alter this part of the screen,
mainly fired by itself.

Sreenlet allow a huge modularity gain in user interface, that way an user action (click on a link, type in a field, ect...)
must not precise the Sreenlet itself but a logical name which can be subscribed by one or more screenlet.

This logical name which is subscribed by screenlet is called `watcherName`, this field is a new attribute for the `container` tag.




== FrontJs Glossary

[#WATCHERS]
watchers:: They are objects stored in js store that can be altered remotely. watcher's subscribers update themselves with the
new value when it change.

[#WATCHERNAME]
watcherName:: It is the key of a watcher







