////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= FrontJs Portal

frontJsPortal component included in frontJsPortal plugin aim to handle user interface with modern javascript framework
(Vue.Js, React, Angular, ect...).

It use portlet/portal system defined by XML and a javascript application.

This component is actually at POC (Proof Of Concept) state, so it aim to show some concrete ideas in order to discuss about them. +
It is produced in an "Agility" spirit which mean that it focus to result in despite of some technical debt.

This documentation aim to,

* Explain the current state of the component, how it work and what points had been choose or took away.
* Prepare future documentation by explaining element meant for future users.

The two main goal of using a javascript framework for user interface is 

1. to have a "modern" look and feel
  * using recent GUI library
  * usable in multiple context (PC, tablet, smartphone) 
1. to increase interactive elements in screen, even if theses screens are based on standard modules :
  * update some part of the screen by action or by data update;
  * modify forms field as function of other field values;
  * simpler screen configuration (portal page) without having to worry about portlets interaction.

include::_include/poc-vuejs_en.adoc[leveloffset=+1]

== modular and generic UI
Aiming to have an open and modular ERP, it's important that the user interface configuration allow to manage multiple screens
from a set of screen "module" for manage *same business object* type in *different business context*.

Next chapters describe a user interface management system's POC aiming to respond to theses modularity needs.

include::Ui-POC.adoc[leveloffset=+2]


== Portlet
Portlet is an autonomous part of the screen, which mean that there can be action that only alter this part of the screen,
mainly fired by itself.

Portlet allow a huge modularity gain in user interface, that way an user action (click on a link, type in a field, ect...)
must not precise the portlet itself but a logical name which can be subscribed one or more portlet.

This logical name which is subscribed by portlets is called `watcherName`, this field is in the association table between
PortalPage and PortalPortlet.

=== Portlet update
It's the update of the data stored in js client side store who trigger portlet render update.


== Portal Page


== FrontJs Glossary

[#WATCHERS]
watchers:: They are objects stored in js store that can be altered remotely. watcher's subscribers update themselves with the
new value when it change.

watchers:: c'est nom du store VueJs utilisé pour stocker les différentes variable sur lequel les container ou portletsont abonné
et donc se mette à jours quand celui-ci change.

[#WATCHERNAME]
watcherName:: It is the key of a watcher







