////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Apache OFBiz® GraphQL plug-in


:imagesdir: ./webapp/graphql/images
image::OFBiz-Logo.svg[100,100][float="left"]
image::graphql-logo.svg[100,100][float="right"]
:uri-demo: https://github.com/girishvasmatkar/graphql-product-api

This plug-in a GraphQL plugin that lets OFBiz to define GraphQL API.

== What's included
* GraphiQL (https://github.com/graphql/graphiql)
* Playground (https://github.com/prisma-labs/graphql-playground)
* OFBiz GraphQL endpoint

== OFBiz GraphQL API based on graphql-java suite of libraries
.The plug-in uses the following dependencies
* com.graphql-java:graphql-java:13.0
* com.graphql-java-kickstart:graphql-java-servlet:9.0.1
* com.graphql-java-kickstart:graphql-java-tools:5.7.1
* io.github.graphql-java:graphql-java-annotations:7.2.1

The endpoint is configured by subclassing SimpleGraphQLHttpServlet from graphql-java-servlet dependency.
----
public class GraphQLEndpointServletImpl extends SimpleGraphQLHttpServlet {
----

== Important URLs
* GraphQL endpint (https://localhost:8443/graphql/api)
* GraphQL schema (https://localhost:8443/graphql/api/schema.json)
* GraphiQL (https://localhost:8443/graphql/control/graphiql)
* GraphQL Playground (https://localhost:8443/graphql/control/playground)

== Usage
It comes with a demo query operation outlined below. The schema part is something that needs to be refined further. Both ways of creating the schema viz. GraphQL SDL and Programmatically using Java API, are demonstrated. This part will be further enhanced to include other operations that can be defined easily.

Queries can be executed like below:
----
'/graphql/?query={graphQLQueryString}' or '/graphql/?query={graphQLQueryString}&&variables={graphQLVariables}&&operationName={operationName}'
----
The bundled up schema does not define any mutation, but executing mutations is supported via POST only as per GraphQL specifications.

=== Demo Query operation
In order to test this plug-in, you need to have a demo plug-in that defines a {uri-demo}[demo] schema with some graphql queries. After deploying the demo, go to https://localhost:8443/graphql/control/graphiql (after authentication) and type in the following in the left papel of graphiql
Input:
----
query {
  productApi{
    product(productId:"WG-9943-B3"){
      productId
      productName
      createdStamp
    }
  }
}
----
Output:
----
{
  "data": {
    "productApi": {
      "product": {
        "productId": "WG-9943-B3",
        "productName": "Giant Widget B3",
        "createdStamp": "2020-08-27T11:10:23Z"
      }
    }
  }
}
----


== Authentication
The GraphQL endpoint is secured. Authentication scheme is "Bearer <JWT>". Every query/muation/subscription operation must have an Authorization header associated with it.
Example Request:

----
GET /graphql/api/?query={
  productApi{
    product(productId:"WG-9943-B3"){
      productId
      productName
      createdStamp
    }
  }
} HTTP/1.1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJBcGFjaGVPRkJpeiIsImlhdCI6MTU0NzczOTM0OCwiZXhwIjoxNjc5Mjc1MzQ4LCJhdWQiOiJ3d3cuZXhhbXBsZS5jb20iLCJzdWIiOiJqcm9ja2V0QGV4YW1wbGUuY29tIiwiR2l2ZW5OYW1lIjoiSm9obm55IiwiU3VybmFtZSI6IlJvY2tldCIsIkVtYWlsIjoianJvY2tldEBleGFtcGxlLmNvbSIsInVzZXJMb2dpbklkIjoiYWRtaW4iLCJSb2xlIjpbIk1hbmFnZXIiLCJQcm9qZWN0IEFkbWluaXN0cmF0b3IiXX0.fwafgrgpodBJcXxNTQdZknKeWKb3sDOsQrcR2vcRw97FznD6mkE79p10Tu7cqpUx7LiXuROUAnXEgqDice-BSg
----
