export default {
  apiUrl: 'https://localhost:8443/examplefjs/control',
  formApiUrl: 'https://localhost:8443/example/control',
  hostUrl: 'https://localhost:8443',
  main: {path: '/main', tokenRequired: false},
  login: {path: '/loginJson', tokenRequired: false},
  ping: {path: '/ping', tokenRequired: false},
  ajaxCheckLogin: {path: '/ajaxCheckLogin', tokenRequired: false},
  showPortlet: {path: '/showPortletFj', tokenRequired: false},
  getCommonUiLabel: '/getCommonUiLabel',

  blockUi: true,
  log: true,

  components: {
    Column: 'vue-column',
    ColumnContainer: 'vue-column-container',
    Container: 'vue-container',
    ContentBegin: 'vue-error',
    DateTimeField: 'vue-date-time-field',
    DisplayField: 'vue-display-field',
    DropDownField: 'vue-drop-down-field',
    FieldGroup: 'vue-field-group', // todo
    FieldRow: 'vue-field-row',
    FieldRowTitleCell: 'vue-field-row-title-cell',
    FieldRowWidgetCell: 'vue-field-row-widget-cell',
    Form: 'vue-form',
    FormatEmptySpace: 'vue-format-empty-space',
    Header: 'vue-header',
    HeaderRow: 'vue-header-row',
    HeaderRowCell: 'vue-header-row-cell',
    FieldTitle: 'vue-field-title',
    HiddenField: 'vue-hidden-field',
    HorizontalSeparator: 'vue-horizontal-separator',
    HyperlinkField: 'vue-hyperlink-field',
    Image: 'vue-error', // not yet implementetd
    ItemRow: 'vue-item-row',
    ItemRowCell: 'vue-item-row-cell',
    Label: 'vue-label',
    Link: 'vue-link',
    ListWrapper: 'vue-list-wrapper',
    LookupField: 'vue-lookup-field',
    Menu: 'vue-menu',
    MenuItem: 'vue-menu-item',
    NextPrev: 'vue-next-prev',
    PasswordField: 'vue-password-field',
    PortalPagePortlet: 'vue-portlet',
    RadioField: 'vue-radio-field',
    Screenlet: 'vue-screenlet',
    SingleWrapper: 'vue-single-wrapper',
    SortField: 'vue-sort-field',
    SubmitField: 'vue-submit-field',
    test: 'test',
    TextAreaField: 'vue-text-area-field',
    TextField: 'vue-text-field',
    TextFindField: 'vue-text-find-field',
    VueJs: 'vue-platform-specific'
  }
};
