import {
  mdiAccountArrowRight,
  mdiAccountCancel,
  mdiAccountGroup,
  mdiArrowCollapse,
  mdiArrowCollapseLeft,
  mdiArrowCollapseRight,
  mdiArrowCollapseUp,
  mdiArrowExpand,
  mdiArrowExpandDown,
  mdiArrowExpandLeft,
  mdiArrowExpandRight,
  mdiArrowLeft,
  mdiArrowRight,
  mdiAt,
  mdiBookAccount,
  mdiCashMultiple,
  mdiCheck,
  mdiClockEnd,
  mdiClose,
  mdiDelete,
  mdiDesktopTower,
  mdiDotsVertical,
  mdiEmail,
  mdiFileCloud,
  mdiFormatListBulleted,
  mdiHelp,
  mdiMapMarker,
  mdiMenu,
  mdiNote,
  mdiNoteText,
  mdiPalette,
  mdiPaperclip,
  mdiPencil,
  mdiPhone,
  mdiPlaylistPlus,
  mdiPlusCircle,
  mdiPuzzle,
  mdiServer,
  mdiSync,
  mdiTargetAccount,
  mdiTextBoxSearch,
  mdiThemeLightDark,
  mdiTimelineText,
  mdiTimetable,
  mdiViewDashboardOutline,
  mdiViewList,
  mdiWeb
} from '@mdi/js'

export default {
  'mdi-account-arrow-right': mdiAccountArrowRight,
  'mdi-account-cancel': mdiAccountCancel,
  'mdi-account-group': mdiAccountGroup,
  'mdi-arrow-collapse': mdiArrowCollapse,
  'mdi-arrow-collapse-left': mdiArrowCollapseLeft,
  'mdi-arrow-collapse-right': mdiArrowCollapseRight,
  'mdi-arrow-collapse-up': mdiArrowCollapseUp,
  'mdi-arrow-expand': mdiArrowExpand,
  'mdi-arrow-expand-down': mdiArrowExpandDown,
  'mdi-arrow-expand-right': mdiArrowExpandRight,
  'mdi-arrow-expand-left': mdiArrowExpandLeft,
  'mdi-arrow-left': mdiArrowLeft,
  'mdi-arrow-right': mdiArrowRight,
  'mdi-at': mdiAt,
  'mdi-book-account': mdiBookAccount,
  'mdi-cash-multiple': mdiCashMultiple,
  'mdi-check': mdiCheck,
  'mdi-clock-end': mdiClockEnd,
  'mdi-close': mdiClose,
  'mdi-delete': mdiDelete,
  'mdi-desktop-tower': mdiDesktopTower,
  'mdi-dots-vertical': mdiDotsVertical,
  'mdi-email': mdiEmail,
  'mdi-file-cloud': mdiFileCloud,
  'mdi-format-list-bulleted': mdiFormatListBulleted,
  'mdi-help': mdiHelp,
  'mdi-map-marker': mdiMapMarker,
  'mdi-menu': mdiMenu,
  'mdi-note': mdiNote,
  'mdi-note-text': mdiNoteText,
  'mdi-palette': mdiPalette,
  'mdi-paperclip': mdiPaperclip,
  'mdi-pencil': mdiPencil,
  'mdi-phone': mdiPhone,
  'mdi-playlist-plus': mdiPlaylistPlus,
  'mdi-plus-circle': mdiPlusCircle,
  'mdi-puzzle': mdiPuzzle,
  'mdi-server': mdiServer,
  'mdi-sync': mdiSync,
  'mdi-target-account': mdiTargetAccount,
  'mdi-text-box-search': mdiTextBoxSearch,
  'mdi-theme-light-dark': mdiThemeLightDark,
  'mdi-timeline-text': mdiTimelineText,
  'mdi-timetable': mdiTimetable,
  'mdi-view-dashboard-outlined': mdiViewDashboardOutline,
  'mdi-view-list': mdiViewList,
  'mdi-web': mdiWeb
}
