////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////

= Contact Mechanism
This screenlet displays the Contact Mechism (adress, telephone, mail, ....)
of a business object: actor, facility, order, ...

Depending on the Contact Mechism
(postal address, email, phone, ...), the display and entry differs.
In all cases, it is possible to clarify the purpose of the Contact Mechism
(billing address, and / or delivery, and / or ...)

A Contact Mechism
may be associated with one or more business object, for example, postal delivery address of a client will also associated with its various orders or quotes.
It is therefore very rare to delete a Contact Mech., it is by cons, possible invalidate it, because each Contact Mech.
possesses the expiry date (from date .. thru date ..)

By default only valid Contact Mechism
are displayed and there is a button to display the history

== Screenlet parameters
* Setting the field Telephone: This field can be detailed by three additional subfield (pay, region, ext), each may or may not be used.
* It is possible to show or not each of the menu options to add
* It is possible, for each type of addition to give a purpose which will be used when creating


== Security rules
* nothing at the screenlet level, only at the update service level (and component rules)


== Technical remarks
This portlet displays the Contact Mechism if it receive a partyId, or a facilityId or a orderId or a workEffortId
