////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Party roles list (and management)
This screenlet list the roles for the party, all or only thus which are part of a role group, the role group description is
displayed in the title of the screenlet, it depends on the setting of the screenlet on this page. 

If there is no role group set, when adding a role, you can start by selecting a parent role and after one child.

If there is a group of role set, when adding a role, it will be possible to choose among the roles that group.

== Limitations or futures functionalities
* Currently, role are group by using parent role, so its not possible for a role to be in multiple "group".

== Screenlet parameters
* Show edit Standard: if set to N then the buttons "Add" and "suppression does not appear.
* Role Group : Indicates the group from which the role will be selectable in the add screen. In this case Party roles list is contain only role which are in the group

== Security rules
* PORTAL_ADMIN is needed to edit portlet attributes
