////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Configurations
The default screen is for the Ebay Configurations tab is 'Ebay Configurations'.
It is used to locate existing configurations that have been created automatically by the system or manually by the user.

It can also be used to create a new configurations or edit to integration between OFBiz and eBay.

== How to find Ebay configurations?
. Select 'product store' you want to see configuration. (Example product store is 'OFBiz E-Commerce Store [9000]')
. Select 'web site' if known.
. Press the 'Search' button to view  configurations.
. Select 'Any' then Press the 'Search' button to view all configurations.

== New/Edit Ebay configurations.
This screen allows the user to create or edit an Ebay Configuration for intregrate ofbiz and Ebay.

Press New on top or 'Edit' button at product store  you want to edit configuration.
System will show screen for edit/create configuration data.

Ebay Configuration use for put keys and certificate get from ebay develop site after you register.

=== How to edit Ebay configurations?
. Please Select 'product store' you want to create configuration. Example product store is 'OFBiz E-Commerce Store [9000]')
. Enter  'Dev Id' (ex:f3586481-93c7-4aaf-ab87-d383d56b71b1)
. Enter  'App Id' (ex:antwebc0f-9bf9-4829-998b-e5e8fb773ac)
. Enter  'Cert Id' (ex:7f363bc0-11d6-489a-a54d-4a44de82f790)
. Enter  'Token' (# token key generated from ebay account ex:AgAAAA**AQAAAA**aAAAAA**Ccn7Sg.....)
. Enter  'Compatibility Level' (ex:635)
. Enter  'Site Id' (ex:0=US ,15=AU)
. Enter  'Xml Gateway Uri' +
         # sandbox -eBayExport.xmlGatewayUri=https://api.sandbox.ebay.com/ws/api.dll +
         # production -eBayExport.xmlGatewayUri=https://api.ebay.com/ws/api.dll)
. Enter  'Custom XML'
. Enter  'Web Site' (ebay)
. Press the 'Update' button to create  configurations.

== Delete Ebay configurations.
. Press 'Delete' button at product store  you want to delete configuration.
