////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Ebay appl. introduction.
Ebay application will be use for merchant integration between OFBiz and eBay.
It is possible to export products from your store into categories on Ebay site  also import an orders from ebay.

You can use fuctions on this application to setup auction on ebay for the sell your stuff on ebay.

== How to setup OFBiz integration eBay.
. Register  with ebay developer site for obtain keys and certificate
  (eBayExport.devId,eBayExport.appId,eBayExport.cerId and eBayExport.token etc.)
  at https://developer.ebay.com/join/[Join with ebay developers]
. After registered it should be following the keys below  :
  * ebay keys example
  .. eBayExport.devID=f3586481-93c7-4aaf-ab87-d383d56b71b1
  .. eBayExport.appID=antwebc0f-9bf9-4829-998b-e5e8fb773ac
  .. eBayExport.certID=7f363bc0-11d6-489a-a54d-4a44de82f790

  * token key generated from ebay account example :
  .. eBayExport.token=AgAAAA**AQAAAA**aAAAAA**Ccn7Sg.....
. Following file in plugins/ebay/config/eBayExport.properties. You will see Merchant  configurations. +
  * For  eBayExport.xmlGatewayUri :
  .. https://api.sandbox.ebay.com/ws/api.dll +
     (sandbox environment used for testing and develoment ) +
     if you want to use for testing should select sandbox enviroment.
  .. https://api.ebay.com/ws/api.dll +
     (production environment).
  * For : eBayExport.siteID    :
  .. It was siteId you want to sell products ex: site id (0=US, 101=Italy, ...) obtain from
     http://developer.ebay.com/DevZone/XML/docs/Reference/eBay/types/SiteCodeType.html[SiteCodeType]
. Go to ebay-->Ebay Configurations screen (see link in the bottom of page) +
  This screen will displayed ebay configurations  with each stores.
  You need to  "`add`" or "`edit`"   the configuration keys you got from ebay for each productstores into this screen.
  This configuration  is for connect to ebay site and export or import data to ebay.
. In eBay screen, go to ebay -> Export  or eBay -> orders Import +
  then try to test export products and import orders from ebay.
