////
Licensed to the Apache Software Foundation (ASF) under one
or more contributor license agreements.  See the NOTICE file
distributed with this work for additional information
regarding copyright ownership.  The ASF licenses this file
to you under the Apache License, Version 2.0 (the
"License"); you may not use this file except in compliance
with the License.  You may obtain a copy of the License at

http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing,
software distributed under the License is distributed on an
"AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
KIND, either express or implied.  See the License for the
specific language governing permissions and limitations
under the License.
////
= Project - summary
This dashboard gives a one page overview of project details, resources, phases and task.
It is also the starting point to navigate to the various sub screens related to a project.

== Sub screens
Following sub screens are provided:

* Gantt chart
* Mailing List
* Phases
* Tasks
* Orders
* Resources
* Content
* Notes
* Sub projects
* Billing

== Project Information
This section provides detailed information about the project, e.g.
the type and scope, the description and planned and actual start and end dates  and planned and actual hours

== Resources
This section provides detailed information about the participants (organizations and persons) of the project.
For the participating persons this section provides information regarding the role in the project and the hours registered
 and processed.

== Sub projects
This section provides detailed information about the project that are registered as sub projects of the project.

== Phases
This section provides an overview of the phases of the project, incl.
status, priority, start and end date and the hours planned and registered.

== Task
This section provides provides an overview of the tasks of the project, incl.
status, priority, start and end date, the first assigned resource and hours planned and registered.

== Notes
This section provides detailed information about notes registered with the project.

== Content
This section provides an overview of content (documents and other files)registered with the project.

== Orders
This section provides an overview of orders linked to the project.